if SERVER then
	AddCSLuaFile 'includes/modules/pon.lua'
	AddCSLuaFile 'includes/modules/xfn.lua'
	AddCSLuaFile 'includes/modules/async.lua'
	AddCSLuaFile 'includes/modules/rpc.lua'
	AddCSLuaFile 'includes/modules/pnet.lua'
	AddCSLuaFile 'includes/modules/pnet_player.lua'
	AddCSLuaFile 'includes/modules/dprint.lua'
	AddCSLuaFile 'includes/modules/path.lua'
	AddCSLuaFile 'includes/modules/netstream.lua'
	AddCSLuaFile 'includes/modules/pstructs.lua'
	AddCSLuaFile 'includes/modules/pcolor.lua'
	AddCSLuaFile 'includes/modules/pdraw.lua'
	AddCSLuaFile 'includes/modules/benchmark.lua'
end
